#!/usr/bin/python
# -*- coding: utf-8 -*-

from stardict import DictMySQL
from stardict import DictCsv
import sys
import time
import os
import io
import csv
import sqlite3
import codecs

if __name__ == '__main__':
    my = {'host':'localhost', 'user':'root','passwd':'123456','db':'skywind_t1','charset':'utf8'}
    def clean():
        dm = DictMySQL(my, init = True)
        dm.delete_all(True)

    def mySQLsearch():
        word=sys.argv[1]
        t = time.time()
        dm = DictMySQL(my, init = True)
        dmw = dm.query(word)
        if dmw is not None:
            print(dmw.get("sw").encode('utf-8'))
            print(dmw.get("definition").encode('utf-8'))
            print(dmw.get("translation").encode('utf-8'))
        else:
            print("Sorry, it cannot find this word!")
        return 0

    def csvSearch():
        word=sys.argv[1]
        csvname = os.path.join(os.path.dirname(__file__), 'dicts/ecdict.csv')
        dc = DictCsv(csvname)
        dmw = dc.query(word)
        if dmw is not None:
            print(dmw.get("sw").encode('utf-8'))
            print(dmw.get("translation").encode('utf-8'))
        else:
            print("Sorry, it cannot find this word!")
        return 0

    mySQLsearch()
    #csvSearch()
