#!/usr/bin/python
# -*- coding: utf-8 -*-

from stardict import DictMySQL
import sys
import time
import os
import io
import csv
import sqlite3
import codecs

if __name__ == '__main__':
    my = {'host':'localhost', 'user':'root', 'db':'skywind_t1'}
    def clean():
        dm = DictMySQL(my, init = True)
        dm.delete_all(True)

    def search():
        word=sys.argv[1]
        t = time.time()
        dm = DictMySQL(my, init = True)
        print(dm.query(word).get("sw"))
        print(dm.query(word).get("definition"))
        return 0
    search()
